# Generated by Django 4.2.7 on 2023-11-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Sin titulo', max_length=200),
            preserve_default=False,
        ),
    ]
